//
//  AccountViewController.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountDisplayLogic: class
{
  func displaySomething(viewModel: Account.Something.ViewModel)
}

class AccountViewController: UIViewController, AccountDisplayLogic
{
  var interactor: AccountBusinessLogic?
  var router: (NSObjectProtocol & AccountRoutingLogic & AccountDataPassing)?

  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Account.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Account.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
