//
//  ServicesInteractor.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ServicesBusinessLogic
{
  func doSomething(request: Services.Something.Request)
}

protocol ServicesDataStore
{
  //var name: String { get set }
}

class ServicesInteractor: ServicesBusinessLogic, ServicesDataStore
{
  var presenter: ServicesPresentationLogic?
  var worker: ServicesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Services.Something.Request)
  {
    worker = ServicesWorker()
    worker?.doSomeWork()
    
    let response = Services.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
