//
//  ServicesPresenter.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ServicesPresentationLogic
{
  func presentSomething(response: Services.Something.Response)
}

class ServicesPresenter: ServicesPresentationLogic
{
  weak var viewController: ServicesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Services.Something.Response)
  {
    let viewModel = Services.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
