//
//  TabBarRouter.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TabBarRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TabBarDataPassing {
  var dataStore: TabBarDataStore? { get }
}

class TabBarRouter: NSObject, TabBarRoutingLogic, TabBarDataPassing {
  weak var viewController: TabBarController?
  var dataStore: TabBarDataStore?

}
