//
//  FreeSMSInteractor.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 25.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

protocol FreeSMSBusinessLogic
{
    func doSomething(request: FreeSMS.Load.Request)
    
    func loadDailySMSLimitInfo(request: FreeSMS.Load.Request)
}

protocol FreeSMSDataStore
{
    var phoneNumber: String { get set }
}

class FreeSMSInteractor: FreeSMSBusinessLogic, FreeSMSDataStore {
    var presenter: FreeSMSPresentationLogic?
    lazy var worker: FreeSMSWorkingLogic = FreeSMSWorker()
    
    var phoneNumber: String = ""
    
    var dailySMSLimitInfo: DailySMSInfoResponse?
    
    
    func loadDailySMSLimitInfo(request: FreeSMS.Load.Request) {
        self.worker.fetchDailySMSLimitInfo({ [weak self] data in
            guard let self = self else { return }
            if let data = data {
                self.dailySMSLimitInfo = data
                let response = FreeSMS.Load.Response(dailySMSLimitInfo: data)
                self.presenter?.presentDailySMSLimitInfo(response: response)
            }
        })
    }
    
    func doSomething(request: FreeSMS.Load.Request)
    {
        
        //    phoneNumber = ""
        //    let response = FreeSMS.Load.Response(phoneNumber: phoneNumber)
        //    presenter?.presentSomething(response: response)
    }
}
