//
//  FreeSMSRouter.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 25.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FreeSMSRoutingLogic
{
    func routeToContacts()
}

protocol FreeSMSDataPassing
{
    var dataStore: FreeSMSDataStore? { get }
}

class FreeSMSRouter: NSObject, FreeSMSRoutingLogic, FreeSMSDataPassing
{
  
    weak var viewController: FreeSMSViewController?
    var dataStore: FreeSMSDataStore?
    
    // MARK: Routing
    
    func routeToContacts() {
        let destinationVC = UserContactsViewController()
        UserContactsConfigurator.configure(destinationVC)
        destinationVC.delegate = viewController
        navigateToContacts(source: viewController!, destination: destinationVC)
    }
    
    func navigateToContacts(source: FreeSMSViewController, destination: UserContactsViewController) {
        source.showDetailViewController(destination, sender: nil)
    }
    
    
    // MARK: Passing data to contacts
    
    func passDataToContacts(source: FreeSMSDataStore, destination: inout UserContactsDataStore) {
//        destination.phoneNumber = source.phoneNumber
    }
}
