//
//  FreeSMSWorker.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 25.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

protocol FreeSMSWorkingLogic {
    func receivePhoneNumber(completion: @escaping (String) -> Void)
    
    func fetchDailySMSLimitInfo(_ completion: @escaping (DailySMSInfoResponse?) -> Void)
}


class FreeSMSWorker: FreeSMSWorkingLogic {
    private let service = App.service
    
    func fetchDailySMSLimitInfo(_ completion: @escaping (NarHubNetworkKit.DailySMSInfoResponse?) -> Void) {
        service.freeSMS.getDailySMSLimitInfo { result in
            switch result {
            case .success(let data):
                completion(data)
            default:
                completion(nil)
            }
            
        }
    }
    
    
    
    func receivePhoneNumber(completion: @escaping (String) -> Void) {
        
    }
}
