//
//  FreeSMSPresenter.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 25.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FreeSMSPresentationLogic {
    func presentSomething(response: FreeSMS.Load.Response)
    
    func presentDailySMSLimitInfo(response: FreeSMS.Load.Response)
}

class FreeSMSPresenter: FreeSMSPresentationLogic {

    weak var viewController: FreeSMSDisplayLogic?
    
    func presentSomething(response: FreeSMS.Load.Response)
    {
        //      let viewModel = FreeSMS.Load.ViewModel(phoneNumber: response.phoneNumber)
        //      viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentDailySMSLimitInfo(response: FreeSMS.Load.Response) {
        guard let infoResponse = response.dailySMSLimitInfo.info else {
            return
        }
        let infoModel = DailySMSInfoModel(title: infoResponse.title ?? "", desc: infoResponse.desc ?? "", smsCount: infoResponse.smsCount ?? "")
        
        let viewModel = FreeSMS.Load.ViewModel(info: infoModel)
        
        viewController?.displayDailySMSLimitInfo(viewModel: viewModel)
    }
}
