//
//  FreeSMSConfigurator.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 25.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class FreeSMSConfigurator
{
    @discardableResult
    static func configure(_ viewController: FreeSMSViewController) -> FreeSMSViewController {
        let view = FreeSMSView()
        let interactor = FreeSMSInteractor()
        let presenter = FreeSMSPresenter()
        let router = FreeSMSRouter()
        
        viewController.mainView = view
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
        
        return viewController
    }
}
