//
//  SupportViewController.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SupportDisplayLogic: class
{
  func displaySomething(viewModel: Support.Something.ViewModel)
}

class SupportViewController: UIViewController, SupportDisplayLogic
{
  var interactor: SupportBusinessLogic?
  var router: (NSObjectProtocol & SupportRoutingLogic & SupportDataPassing)?

  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Support.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Support.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}



