//
//  SupportPresenter.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SupportPresentationLogic
{
  func presentSomething(response: Support.Something.Response)
}

class SupportPresenter: SupportPresentationLogic
{
  weak var viewController: SupportDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Support.Something.Response)
  {
    let viewModel = Support.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
