//
//  SupportInteractor.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SupportBusinessLogic
{
  func doSomething(request: Support.Something.Request)
}

protocol SupportDataStore
{
  //var name: String { get set }
}

class SupportInteractor: SupportBusinessLogic, SupportDataStore
{
  var presenter: SupportPresentationLogic?
  var worker: SupportWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Support.Something.Request)
  {
    worker = SupportWorker()
    worker?.doSomeWork()
    
    let response = Support.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
