//
//  DashboardWorker.swift
//  Nar_Hub
//
//  Created by Sevar Jafarli on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit


protocol DashboardWorkingLogic {
    func fetchHubServices(_ completion: @escaping (HubResponse?) -> Void)
    
    func fetchStories(_ completion: @escaping (StoriesResponse?) -> Void)
}


class DashboardWorker: DashboardWorkingLogic {
    private let service = App.service
    
    func fetchHubServices(_ completion: @escaping (HubResponse?) -> Void) {
        service.hub.getHubServices { result in
            switch result {
            case .success(let data):
                completion(data)
            default:
                completion(nil)
            }
        }
    }
    
    func fetchStories(_ completion: @escaping (StoriesResponse?) -> Void) {
        service.story.getStories { result in
            switch result {
            case .success(let data):
                completion(data)
            default:
                completion(nil)
            }
        }
    }
}
